# Bonus Depreciation

'2025':
  3-year:  0
  5-year:  0
  7-year:  0
  10-year: 0
  15-year: 0
  20-year: 0
  
'2028':
  3-year:  .8
  5-year:  .8
  7-year:  .8
  10-year: .8
  15-year: .8
  20-year: .8

