---
model_version: 1

runtime_options: 
  user_id: jmk263
  write_locally: True
  
dependency_info:
  Depreciation:
    type: raw_data
    version: test
    vintage: 2022
    scenario: historical
  Macro-Projections:
    type: model_data
    version: 3
    vintage: 2024021509
    scenario: baseline

