---

roots: 
  input: './resources/input'
  output: './resources/output'

dependencies:
  Investment-Projections: '/model_data/Investment-Projections/v1/2024100807/baseline'
  Macro-Projections: '/model_data/Macro-Projections/v3/2024100910/baseline'
